// Landlord draft generator — takes a set of violations and the original clauses,
// and uses the LLM to produce a fully rewritten, legally compliant lease draft.

import { callGemini, callGeminiJSON } from './gemini.js';
import { jsPDF } from 'jspdf';

/**
 * Generate a legally compliant lease draft from violations and original clauses.
 * @param {Array} clauses - The original parsed clauses from the lease.
 * @param {Array} violations - The violations found in the lease.
 * @param {string} jurisdictionId - e.g. 'IN', 'UG'
 * @returns {Promise<{ sections: Array, pdfBuffer: Buffer, summaryText: string }>}
 */
export async function generateCompliantDraft(clauses, violations, jurisdictionId) {
  const violatedClauseIds = new Set(violations.map((v) => v.clause_id));

  // Build a structured view of clauses + their issues
  const clauseSummary = clauses.map((c) => {
    const relatedViolations = violations.filter((v) => v.clause_id === c.clause_id);
    return {
      clause_id: c.clause_id,
      original_text: c.text,
      has_violations: relatedViolations.length > 0,
      violations: relatedViolations.map((v) => ({
        severity: v.severity,
        explanation: v.explanation,
        legal_reference: v.legal_reference,
      })),
    };
  });

  const prompt = `
You are a senior tenancy law expert specialising in the legal framework of jurisdiction: ${jurisdictionId}.

A landlord has submitted a draft lease agreement with the following clauses. Some clauses have been flagged as legally non-compliant.

Your task is to produce a COMPLETE, REDRAFTED, LEGALLY COMPLIANT lease agreement. For each violated clause, replace it with a legally sound version. For compliant clauses, keep them unchanged (you may lightly improve the language for clarity).

ORIGINAL CLAUSES WITH VIOLATION DETAILS:
${JSON.stringify(clauseSummary, null, 2)}

Return a JSON object in EXACTLY this format:
{
  "summary": "A 2-3 sentence overview of the key changes made and why the draft is now compliant.",
  "changes_count": <number of clauses that were changed>,
  "sections": [
    {
      "clause_id": "the original clause_id",
      "title": "A short descriptive title for this clause (e.g. 'Security Deposit', 'Entry Rights')",
      "original_text": "the original clause text",
      "redrafted_text": "the new legally compliant text",
      "was_changed": true/false,
      "change_reason": "Brief explanation of why this was changed (null if unchanged)",
      "legal_basis": "The legal provision this complies with (null if unchanged)"
    }
  ]
}

RULES:
- Every clause from the input MUST appear in sections[], in the same order.
- If a clause is compliant, set was_changed: false and set redrafted_text = original_text.
- Redrafted clauses MUST cite the specific law/section they comply with in legal_basis.
- The redrafted_text must be professional, clear, and legally sound — suitable for an actual lease.
- Do NOT add new clauses that weren't in the original.
- Respond with ONLY the JSON object. No markdown, no preamble.
`;

  const draftJson = await callGeminiJSON(prompt);

  // Validate the response structure
  if (!draftJson.sections || !Array.isArray(draftJson.sections)) {
    throw new Error('LLM returned an invalid draft format. Please try again.');
  }

  // Generate PDF
  const pdfBuffer = generateDraftPdf(draftJson, jurisdictionId);

  return {
    sections: draftJson.sections,
    summary: draftJson.summary,
    changes_count: draftJson.changes_count || draftJson.sections.filter((s) => s.was_changed).length,
    pdfBuffer,
  };
}

/**
 * Render the draft to a PDF using jsPDF.
 */
function generateDraftPdf(draft, jurisdictionId) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addText = (text, size = 10, style = 'normal', color = [30, 30, 30]) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(String(text || ''), contentWidth);
    lines.forEach((line) => {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += size * 0.42;
    });
    y += 2;
  };

  const addDivider = () => {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 4;
  };

  // Header
  addText('LEGALLY COMPLIANT LEASE DRAFT', 16, 'bold', [37, 99, 235]);
  addText(`Generated by RentRight • Jurisdiction: ${jurisdictionId}`, 8, 'normal', [100, 100, 100]);
  addText(`Date: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 8, 'normal', [100, 100, 100]);
  y += 3;
  addDivider();

  // Summary
  addText('SUMMARY OF CHANGES', 11, 'bold', [37, 99, 235]);
  addText(draft.summary, 10, 'normal');
  addText(`Total clauses modified: ${draft.changes_count}`, 10, 'bolditalic', [100, 100, 100]);
  y += 2;
  addDivider();

  // Clauses
  draft.sections.forEach((section, i) => {
    // Clause title
    const titleColor = section.was_changed ? [220, 38, 38] : [30, 30, 30];
    addText(`${i + 1}. ${section.title}${section.was_changed ? '  [REVISED]' : ''}`, 11, 'bold', titleColor);

    if (section.was_changed) {
      addText('▸ REDRAFTED (Compliant Version):', 9, 'bold', [22, 163, 74]);
      addText(section.redrafted_text, 10, 'normal', [30, 30, 30]);

      if (section.legal_basis) {
        addText(`Legal basis: ${section.legal_basis}`, 8, 'italic', [100, 100, 100]);
      }

      if (section.change_reason) {
        addText(`Why changed: ${section.change_reason}`, 8, 'italic', [120, 80, 0]);
      }
    } else {
      addText(section.redrafted_text, 10, 'normal', [60, 60, 60]);
    }

    y += 2;
    if (i < draft.sections.length - 1) {
      doc.setDrawColor(230, 230, 230);
      doc.line(margin, y, pageWidth - margin, y);
      y += 4;
    }
  });

  // Footer
  y += 5;
  addDivider();
  addText(
    'This document was generated by RentRight AI. It is intended as a starting point for a legally compliant lease ' +
    'and should be reviewed by a qualified legal professional before use.',
    7, 'italic', [130, 130, 130]
  );

  return Buffer.from(doc.output('arraybuffer'));
}
